# Generated by Django 5.0 on 2023-12-22 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AHNapp.user')),
                ('position', models.CharField(max_length=200)),
            ],
            bases=('AHNapp.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AHNapp.user')),
                ('GPA', models.FloatField()),
                ('CoursesList', models.TextField()),
            ],
            bases=('AHNapp.user',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=200)),
                ('CourseCode', models.CharField(max_length=200)),
                ('CourseWeight', models.FloatField()),
                ('CourseGrade', models.FloatField()),
                ('isReg', models.BooleanField(default=False)),
                ('Studentid', models.ManyToManyField(related_name='Studentid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
