# Generated by Django 5.0 on 2023-12-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHNapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseTitle', models.CharField(max_length=200)),
                ('Courseid', models.AutoField(primary_key=True, serialize=False)),
                ('CourseWeight', models.FloatField()),
                ('CourseGrade', models.FloatField()),
            ],
        ),
    ]
