# Generated by Django 5.0 on 2023-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHNapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isReg',
            field=models.BooleanField(default=False),
        ),
    ]
