# Generated by Django 5.0 on 2023-12-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHNapp', '0003_course_isreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Studentid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AHNapp.student'),
        ),
    ]
