# Generated by Django 5.0 on 2023-12-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHNapp', '0004_course_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Courseid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseCode',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
